name: slp
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8.0
  - pandas=1.2.4
  - scipy=1.6.2
  - pytest=6.2.4
  - pytest-cov=2.12.1
  - mypy=0.910
  - data-science-types=0.2.23
  - pip=21.2.2
  - pyqt>=5.9.2,<6.0.0
  - pyqtgraph>=0.11.0
  - colorcet=2.0.6
  - jsonschema=3.2.0
  - tqdm>=4.62.0
  - ipython>=7.9.0
  - notebook>=6.4.0
  - pip:
      - pytype==2021.07.19
      - iteround==1.0.2
      - dill==0.3.4